import type { Metadata } from "next";
import { Mulish } from 'next/font/google';
import "./globals.css";

const mulish = Mulish({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: "Student Portal",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className={`${mulish.className} antialiased text-gray-700`}>
        {children}
      </body>
    </html>
  );
}

export default RootLayout;
